### ISSUE TITLE
Add loading bars showing accurate downloading of models on try/<modelname> pages.

### ISSUE THREAD

**Issue by ashinsabu** [ashinsabu/monkeypox-detection#1]
The model download can take a while and currently displays the following. 
![image](https://github.com/ashinsabu/monkeypox-detection/assets/38109596/d9b4927c-103a-4f91-8fd8-3f4c9c45f1a4)
An accurate loading bar can be added(since it uses fetch behind the scenes and accurate loading progress can be displayed using the  onProgress callback as an option)

References: 

https://js.tensorflow.org/api/latest/#loadLayersModel
https://github.com/tensorflow/tfjs/issues/336

**Comment by deedee1122** [comment]
Hello I would like to work on these, can you assign it to me. Thank you

**Comment by ashinsabu** [comment]
Go ahead @deedee1122 !
